# Form implementation generated from reading ui file '/Users/panh/PycharmProjects/PythonProject/Chapter5/ex73/ui/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 299)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.aLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.aLabel.setObjectName("aLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.aLabel)
        self.aLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.aLineEdit.setObjectName("aLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.aLineEdit)
        self.bLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.bLabel.setObjectName("bLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.bLabel)
        self.bLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.bLineEdit.setObjectName("bLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.bLineEdit)
        self.cLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.cLabel.setObjectName("cLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cLabel)
        self.cLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cLineEdit.setObjectName("cLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cLineEdit)
        self.resultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultLabel.setObjectName("resultLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.resultLabel)
        self.resultLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.resultLineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Quadratic equation</span></p></body></html>"))
        self.aLabel.setText(_translate("MainWindow", "a:"))
        self.bLabel.setText(_translate("MainWindow", "b:"))
        self.cLabel.setText(_translate("MainWindow", "c:"))
        self.resultLabel.setText(_translate("MainWindow", "Result:"))
        self.pushButton.setText(_translate("MainWindow", "Calculation"))
